# ===============================
# DEV DATABASE CONFIG (USING ENV VARIABLES)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/payroll_service
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ===============================
# LOGGING
# ===============================
logging.level.root=INFO
logging.level.com.bridgelabz=DEBUG